### PR TITLE
Update to correct repository URL

### PR DESCRIPTION
**Pull request by johanno**
The current url is wrong.

### CODE REVIEW

**Comment by johanno** [comment]
ok github did not work here for me. I'll retry

**Comment by johanno** [comment]
OK it is already fixed on master. I am stupid

**Comment by revam** [comment]
🤔

**Comment by johanno** [comment]
> 🤔

https://docs.shokoanime.com/shokofin/install/

Still shows the wrong json for the repo. And I wanted to fix it. However it is already fixed in the master and I made a commit without any changes, which really did put me off.

**Comment by revam** [comment]
@ElementalCrisis any idea why the changes aren't pushed yet?

**Comment by revam** [comment]
@johanno I'll give you A for effort though.

**Comment by harshithmohan** [comment]
@johanno The docs are fixed now 😔

**Pull request closed without merging**
