### PR TITLE
Major Server Docs Layout Changes. Added Server Documentation.

### PR DESCRIPTION
**Pull request by asmoranomar**
Renamed files within the server folder to better identify with the topics they cover.
Created Preinstallation section.
Moved Database topics to Preinstallation section.
Added SQLite topic to Preinstallation section.
Clarified all sections regarding topics for Shoko Server for Windows or Linux.
Under Shoko Server for Linux, added a step-by-step guide for installing on Synology NAS.
Added Section on Configuration for Shoko Server on Linux.
Added Placeholder for installing WebUI.
Added Placeholder for configurations in WebUI.

I believe, all links have been changed to reflect the new names.  But just a warning that it is possible I may have missed some.

### CODE REVIEW

**Comment by ElementalCrisis** [comment]
Thanks for the submissions. 

A few things to change and/or fix. 

- You can remove the Web UI placeholder pages, the Web UI is intended to replace the current Server GUI and with the content being the same, its just a matter of updating the current docs with the new locations and pictures.
- **Preinstallation - Database Setup** can just be **Database Setup**.
- The **MySQL** and the **NAS Specific Documentation** links are incorrect. 
- Change **NAS Specific Documentation** to something like **Shoko Server On NAS**.
- The **Why DB** sections contain pretty outdated info, though that's not on you. 
- **Configuring Shoko Server** seems cluttered, the removal of the Web UI links as mentioned above will help but it can be further simplified by removing **Configuring Shoko Server** and just having the two sections be parent menus.

EDIT:

What you could also do is add the Installing Web UI info to the **linux_install.html** page.

**Comment by asmoranomar** [comment]
- WebUI placeholders removed.
- **Preinstallation -Database Setup** is now named **Database Setup**
- Links to **MySQL** and other misc links have been fixed. **NAS Specific Documentation** has been removed.
- **Configuring Shoko Server** has been changed back to it's original layout.
- I have successfully merged the **linux_install, linux_synology, and linux_config** files together.  It is quite big and very detailed, so please let me know if there is any way I can further improve it.
- Per our discussions on the teams vision behind Shoko Server, it's development, the design concepts for WebUI, and other misc thoughts; **I have reverted the naming scheme back to it's original layout,** with the exception of the install instructions.  I have once again renamed these two files, instead of linux_install and windows_install, they are now **install_linux** and **install_windows**.
- I linked the url to **WebUI** download when discussing the setup parameters for WebUI, but I did not discuss how to install WebUI.
  - If we are going to discuss installation, I'd rather put the placeholders back and start building on them since it applies to all versions of Shoko Server.  I can start another branch and do that.
  - If we aren't, then we should probably just leave it at that, or even remove the WebUI link and simply mention that it is a feature being developed.

This is actually quite fun - let me know your thoughts.

**Comment by asmoranomar** [comment]
- Updated **install_linux** to resolve conflict from 7fe3904 commit.  A force will be needed resolve this conflict since the filename changed (unless you can teach me how to get around that?)

**Comment by ElementalCrisis** [comment]
What you'll need to do is pull in the latest commits, then re-apply your changes to resolve the merging conflict.

**Pull request merged**
