### PR TITLE
Add instructions for installing ShokoServer bare-metal for Ubuntu

### PR DESCRIPTION
**Pull request by ChrisP99**
I noticed that the docs say:

```
Running Shoko directly on Linux (bare metal) is not advised due to the additional
complexity and skill required for proper installation.
```
 but don't actually say how to do so. I'm not sure if that's intentional or not, but I decided to throw together some instructions for how I installed it bare-metal on my Ubuntu server. I also added a warning advising that this way isn't actually recomended, and that you would need to manually update ShokoServer to get continuous updates (please correct me if I'm wrong there.)

Feel free to close this if you don't want this to be included in your documentation.

Thanks!

### CODE REVIEW

**Comment by da3dsoul** [comment]
I would change the "username", which isn't indicated to be replaced to 1000, the default user id on Ubuntu. (Tell me if I'm wrong)

**Comment by ChrisP99** [comment]
That's right! I modified that line to refer to `User=1000` and added a message saying it can be changed if needed.

**Comment by da3dsoul** [comment]
Ah, also, it'll probably come up. People that would go this far out of their way would probably want dailies, as well. I would add a note to the section to download the latest release to have a version with the latest daily release

**Review by revam — COMMENTED** [review]
I'll just add my two cents; putting it in the docs — even if we warn the user that it's not _recommended_ — would seem to me like we support this kind of setup, which we still don't as far as my understanding goes. Unless we want to change that with this PR then I would rather not  document it. 

Also since we're installing the framework (which is needed for avd3 to work), then we can download the framework dependent release instead of the linux standalone one.

**Comment by ChrisP99** [comment]
In my case, I manage my server using LXD and all of my instances of stuff related to streaming (Plex etc.) are in a single LXC container. I don't really like using Docker as it would essentially mean containerizing ShokoServer twice, hence me running it bare-metal on the container.

I do think a lot of people would prefer running ShokoServer directly themselves, as not everyone is a fan of Docker instances, but I completely get where you're coming from when you don't want to support people's random Linux questions if they're not familiar with it.

Let me know if you want the documentation to be updated more to make it explicltly clear there would be no support provided, and also for the instructions to download the correct dependancies to be changed (like for avd3 above)

Otherwise feel free to close the PR if you don't want this to be in the documentation 😊

**Comment by revam** [comment]
I'm not for or or against adding the instructions, but I were just pointing out that from my POV, then adding the instructions is the same as saying we support this kind of setup, since we documented it.

Can other team members give their input/thoughts about adding or not adding it please? 
@ShokoAnime/developers

**Comment by harshithmohan** [comment]
> I'm not for or or against adding the instructions, but I were just pointing out that from my POV, then adding the instructions is the same as saying we support this kind of setup, since we documented it.
> 
> Can other team members give their input/thoughts about adding or not adding it please? @ShokoAnime/developers

It cannot be worse than having truenas, synology and qnap instructions right? .. right?

**Comment by da3dsoul** [comment]
I'm not against putting instructions for one situation we actually know well. We just won't help with perms and dependency issues

**Comment by ElementalCrisis** [comment]
Agree with @da3dsoul, 

@ChrisP99 update the warning to this and then we can merge it.

```
This option is not recommended because it requires manual updates whenever a new version is released, as automatic updates are not available.

Additionally, a strong understanding of Linux is needed to follow these steps and troubleshoot any issues that may occur. Please note that we are unable to provide direct support for installations performed using this method.
```

**Comment by harshithmohan** [comment]
Also place it at the end, below TrueNAS

**Comment by ElementalCrisis** [comment]
PR Merged.

Thanks @ChrisP99 for the contribution, feel free to add more, lol. :)

**Pull request merged**
